version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: blocksight-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
