name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend-checks:
    name: Backend Typecheck, Lint, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend deps (CI)
        working-directory: backend
        run: npm install --no-audit --no-fund

      - name: Typecheck
        working-directory: backend
        run: npm run typecheck

      - name: Lint
        working-directory: backend
        run: npm run lint

      - name: Build
        working-directory: backend
        run: npm run build

      - name: Test
        working-directory: backend
        run: npm test

